[versions]
shadow = "9.3.0"
paperPluginYml = "0.6.0"
paper = "1.21.8-R0.1-SNAPSHOT"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
bukkitPluginYml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "paperPluginYml" }
